### ISSUE TITLE
Виден только первый plunker

### ISSUE THREAD

**Issue by Gorfix** [AnteaterKit/angular2-yandex-maps#15]
Добрый день.
Получается посмотреть только demo 1. В остальных в логах ошибка
Error: (SystemJS) ReferenceError: exports is not defined
	    at eval (https://unpkg.com/angular2-yandex-maps/lib/ya-maps-types.js:2:23)
	    at eval (<anonymous>)
	    at Object.eval (https://unpkg.com/angular2-yandex-maps/lib/core.module.js:19:10)
	    at eval (https://unpkg.com/angular2-yandex-maps/lib/core.module.js:56:4)
	Evaluating https://unpkg.com/angular2-yandex-maps/lib/ya-maps-types.js
	Evaluating https://unpkg.com/angular2-yandex-maps/lib/core.module.js
	Evaluating https://unpkg.com/angular2-yandex-maps/index.js
	Error loading https://run.plnkr.co/bFDWTNEZ2SXFOR1I/src/main.ts
ZoneDelegate.invoke @ unpkg.com/zone.js@0.8.17/dist/zone.js:392

И карта справа пустая. Подскажите пожалуйста как исправить. Браузер chrome 60.0.3112.113.

**Comment by Gorniv** [comment]
надо добавить на index.html
```html
<script >
      let exports = {};
</script>
```
Саня, поправь примеры.

**Comment by AnteaterKit** [comment]
Обновил
