### ISSUE TITLE
Нулевая высота карты (angular 5)

### ISSUE THREAD

**Issue by martrix78** [AnteaterKit/angular2-yandex-maps#21]
добрый день, пытаюсь показать карту
` <ya-map #map [latitude]="currentPosition.lat" [longitude]="currentPosition.lng" >
      <ya-marker [latitude]="currentPosition.lat" [longitude]="currentPosition.lng"></ya-marker>
 </ya-map>`
карта и маркер отображается, но нулевой высоты.
как это можно подправить?

**Comment by martrix78** [comment]
проблема в ymaps.js строка 97
если в шаблоне указать стиль **style='width: 100%; height: 100%;'**
`<div style='width: 100%; height: 100%;' class=\"map-container-inner\" id=\"map\" > ...`
то карта выводится

**Comment by enthusasist** [comment]
Добрый день! Столкнулся с такой же проблемой, используя angular2-yandex-maps. Подскажите пожалуйста, удалось ли вам исправить нулевую высоту карты?
Пробовал так:
```
<div style="width: 100%; height: 100%;" class="map-container-inner" id="map">
  <ya-map [latitude]="55.0" [longitude]="48.0" [zoom]="11"></ya-map></div>
```
Получаю "height: 0px" в классах
"ymaps-2-1-64-map" и 
"ymaps-2-1-64-map ymaps-2-1-64-i-ua_js_yes ymaps-2-1-64-map-bg ymaps-2-1-64-islets_map-lang-ru"

**Comment by martrix78** [comment]
Я просто начал использовать яндекс карты без этого компонента

**Comment by enthusasist** [comment]
Т.е. без использования angular2-yandex-maps?
Через JavaScript api? (https://tech.yandex.ru/maps/jsbox/2.1/mapbasics)

**Comment by martrix78** [comment]
Да, именно так. Просто делаете свой компонент
