### ISSUE TITLE
Disable controlls

### ISSUE THREAD

**Issue by 10on** [AnteaterKit/angular2-yandex-maps#6]
How I can disable all controls?

I'm trying use empty array as argument, as ussialy in JS library, but not result

Thanks!

**Comment by AnteaterKit** [comment]
Hello!

Set some controls like:
template: `
    <ya-map [latitude]="55.76" [longitude]="37.64" [controls]="['zoomControl', 'searchControl']">
.....
 </ya-map>

Disable all is not available now, it's bug
    <ya-map [latitude]="55.76" [longitude]="37.64" [controls]="['']">
 </ya-map>
It's hide control, but exception appears.
I fix it in several hours.

Thank you!

**Comment by AnteaterKit** [comment]
fix <ya-map [latitude]="55.76" [longitude]="37.64" [zoom]="6" [panToObjects]="panToObjects" [controls]="[]">
